### ISSUE TITLE
github action: todo to issue

### ISSUE THREAD

**Issue by mattermat** [deltaleap/stream-tools#18]
add a github action to convert todos in issues

**Comment by mattermat** [comment]
```
name: "Maintenance"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v2.3
```
